# ===============================
# Datasource - PostgreSQL (PROD)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/controle_cfc
spring.datasource.username=
spring.datasource.password=

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# ===============================
# JWT
# ===============================

jwt.secret=
jwt.expiration=