# ===============================
# Datasource - PostgreSQL (PROD)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/controle_cfc
spring.datasource.username=
spring.datasource.password=

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# ===============================
# JWT (Alterar depois)
# ===============================

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Por enquanto
app.security.cookie.secure=false 

# ===============================
# SERVIÇO DE EMAIL
# ===============================

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# FRONTEND
# ===============================

app.url-frontend=http://localhost:5173

# ===============================
# SUPER-ADMIN
# ===============================

app.superadmin.name=Lucas Admin
app.superadmin.email=sistema@controlecfc.com
app.superadmin.password=${ADMIN_PASS}
app.superadmin.phone=${ADMIN_PHONE}