# ===============================
# Datasource - H2 (DEV)
# ===============================
spring.datasource.url=jdbc:h2:mem:controlecfc
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ===============================
# H2 Console
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# JWT (Alterar depois)
# ===============================

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Por enquanto
app.security.cookie.secure=false 

# ===============================
# SERVIÇO DE EMAIL
# ===============================

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# FRONTEND
# ===============================

app.url-frontend=http://localhost:5173

# ===============================
# SUPER-ADMIN
# ===============================

app.superadmin.name=Lucas Admin
app.superadmin.email=sistema@controlecfc.com
app.superadmin.password=${ADMIN_PASS}
app.superadmin.phone=${ADMIN_PHONE}