# ===============================
# Datasource - H2 (DEV)
# ===============================
spring.datasource.url=jdbc:h2:mem:controlecfc
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ===============================
# H2 Console
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# JWT
# ===============================

jwt.secret=bWluaGFDaGF2ZVNlY3JldGFNdWl0b0RpZmljaWxEZVF1ZWJyYXIxMjM0NTY=
jwt.expiration=86400000

app.security.cookie.secure=false

# ===============================
# SERVIÇO DE EMAIL
# ===============================

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=e14b80c10d5ab7
spring.mail.password=3e2086efb976f4
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# FRONTEND
# ===============================

app.url-frontend=http://localhost:5173

# ===============================
# SUPER-ADMIN
# ===============================

app.superadmin.name=Lucas Admin
app.superadmin.email=sistema@controlecfc.com
app.superadmin.password=botafogo2024
app.superadmin.phone=84994885834